src/objects/Account.object
<CustomObject>
    <recordTypes>
        <fullName>Seller</fullName>
        <active>true</active>
        <label>Lojista</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Case.object
<CustomObject>
    <recordTypes>
        <fullName>MktPlace_DuvidasProdutos</fullName>
        <active>true</active>
        <businessProcess>MktPlace Dúvidas de Produtos %2F Posição de entrega</businessProcess>
        <label>MktPlace - Dúvidas gerais</label>
    </recordTypes>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

src/objects/CaseComment__c.object
<CustomObject>
    <fields>
        <fullName>Autor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Autor</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>ComentariosCaso</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Caso__c</fullName>
        <label>Caso</label>
        <referenceTo>Case</referenceTo>
        <relationshipName>ComentariosCaso</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Comentario__c</fullName>
        <label>Comentário</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Private__c</fullName>
        <defaultValue>true</defaultValue>
        <description>É uma mensagem para o logista?</description>
        <label>Mensagem para o logista</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>TipoAutor__c</fullName>
        <label>Tipo Autor</label>
        <picklist>
            <picklistValues>
                <fullName>Lojista</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cliente</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Magazine Luiza</fullName>
                <default>true</default>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Comentário do Caso</label>
    <nameField>
        <label>ID-Comentario</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Comentários do Caso</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>CPF_CNPJ__c</fullName>
        <externalId>true</externalId>
        <label>CPF / CNPJ</label>
        <length>20</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Gender__c</fullName>
        <label>Sexo</label>
        <picklist>
            <picklistValues>
                <fullName>Masculino</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Feminino</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/CaseMilestoneDAOTest.cls
@isTest
private class CaseMilestoneDAOTest {
	
	private static Case case01;
	private static Account customer, seller, mktplace;
	
	static {
		String cnpj = Utils.generateCnpj();
		
		customer = AccountBuild.createCustomerAcct();
		seller = AccountBuild.createSellerAcct(cnpj);
		mktplace = AccountBuild.createMktPlaceAcct();
		Database.insert(new List<Account>{customer, seller, mktplace});
		
		Contact contactSeller = new Contact(
			FirstName = 'Suene',
			LastName = 'Souza',
			CPF_CNPJ__c = cnpj,
			Email = 'suene.souza@luizalabs.com',
			AccountId = seller.Id,
			Phone = '11'+Utils.randomNumberAsString(8),
			MobilePhone = '119'+Utils.randomNumberAsString(8),
			Gender__c = 'Feminino'
		);
		Database.insert(contactSeller);
		
		case01 = CaseBuild.createCase('MktPlace_DuvidasProdutos', seller.Id, contactSeller.Id);
		Database.insert(case01);
		
		Database.insert(new CaseComment__c(
			Caso__c = case01.Id,
			Autor__c = customer.Id,
			Name = 'Name',
			Comentario__c = 'Comentario teste cliente',
			TipoAutor__c = 'Cliente',
			Private__c = false
		));
	}
	
	
	@isTest static void test_method_one() {
		CaseMilestoneDAO.getCaseMilestonesByCaseId(new Set<Id>{case01.Id});
	}
	
}