src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>LuizaCode__c</fullName>
        <externalId>true</externalId>
        <label>LuizaCode</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>ContactSeller__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contato do Lojista</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Casos (Contato do Lojista)</relationshipLabel>
        <relationshipName>ContatoSeller</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>LuizaCode__c</fullName>
        <externalId>true</externalId>
        <label>LuizaCode</label>
        <length>150</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>MagazineMediation__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Mediação Magazine Luiza?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>OrderNumber__c</fullName>
        <label>Número do Pedido</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ProtocoloAtendimento__c</fullName>
        <label>Protocolo de atendimento</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Seller__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Lojista</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Casos (Logista)</relationshipLabel>
        <relationshipName>CasosSeller</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ServiceRating__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Nota do Atendimento</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

src/objects/CaseComment__c.object
<CustomObject>
    <fields>
        <fullName>Autor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Autor</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>ComentariosCaso</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Caso__c</fullName>
        <label>Caso</label>
        <referenceTo>Case</referenceTo>
        <relationshipName>ComentariosCaso</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Comentario__c</fullName>
        <label>Comentário</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>MagazineMediation__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Precisa da mediação do Magazine?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Private__c</fullName>
        <defaultValue>true</defaultValue>
        <description>É uma mensagem para o logista?</description>
        <label>Mensagem para o logista</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>TipoAutor__c</fullName>
        <label>Tipo Autor</label>
        <picklist>
            <picklistValues>
                <fullName>Lojista</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cliente</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Magazine Luiza</fullName>
                <default>true</default>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Comentário do Caso</label>
    <nameField>
        <label>ID-Comentario</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Comentários do Caso</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>LuizaCode__c</fullName>
        <externalId>true</externalId>
        <label>LuizaCode</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/MktPlace_CaseInboundIntegrationBO.cls
/**
*	@author Diego Moreira
*	@class Classe de negocio para leitura do dados de integração 
*/
public class MktPlace_CaseInboundIntegrationBO {
	/**
	*	Metodo principal de leitura e fechamento do atendimento por solicitação do usuario
	*	CASO Adionado a nota e alterando o status de atendimento para fechado
	*	COMENTARIO Adicionado notas finais do atendimento
	*	@param payload JSON com os dados de fechamento do atendimento
	*/ 
	public static void caseClose( String payload ) {
		Map<String, Object> mapResult = ( Map<String, Object> ) JSON.deserializeUntyped( payload );
		Map<String, Object> mapCloseCaseResult = ( Map<String, Object> ) mapResult.get( 'closingCase' );

		Case caseToUpdate = new Case();
		caseToUpdate.LuizaCode__c 		= Util.getString( mapCloseCaseResult.get( 'idCase' ) );
		caseToUpdate.ServiceRating__c 	= Util.getDecimal( Util.getString( mapCloseCaseResult.get( 'rating' ) ) );
		caseToUpdate.Status 			= 'Fechado Cliente';

		CaseComment__c caseCommentToInsert = new CaseComment__c();
		caseCommentToInsert.Autor__r 				= new Account( LuizaCode__c = Util.getString( mapCloseCaseResult.get( 'idAuthor' ) ) );
		caseCommentToInsert.Caso__r 				= new Case( LuizaCode__c = Util.getString( mapCloseCaseResult.get( 'idCase' ) ) );
		caseCommentToInsert.Comentario__c 			= Util.getString( mapCloseCaseResult.get( 'comment' ) );
		caseCommentToInsert.TipoAutor__c 			= 'Cliente';

		CaseDAO.getInstance().insertData( caseCommentToInsert );
		upsert caseToUpdate LuizaCode__c;
	}

	/**
	*	Cria os dados de atendimento 
	*	@param mapCaseResult mapa com os valores do atendimento
	*/
	public static void caseNew( Map<String, Object> mapCaseResult ) {
		Case caseToUpsert = new Case();
		caseToUpsert.RecordTypeId 				= Schema.SObjectType.Case.getRecordTypeInfosByName().get( Util.getString( mapCaseResult.get( 'caseType' ) ) ).getRecordTypeId();
		caseToUpsert.LuizaCode__c 				= Util.getString( mapCaseResult.get( 'protocolService' ) );
		caseToUpsert.Account 					= new Account( LuizaCode__c = Util.getString( mapCaseResult.get( 'idAccount' ) ) );
		caseToUpsert.Seller__r					= new Account( LuizaCode__c = Util.getString( mapCaseResult.get( 'idSeller' ) ) );
		caseToUpsert.ContactSeller__r			= new Contact( LuizaCode__c = Util.getString( mapCaseResult.get( 'idContactSeller' ) ) );	
		caseToUpsert.ProtocoloAtendimento__c 	= Util.getString( mapCaseResult.get( 'protocolService' ) );
		caseToUpsert.OrderNumber__c 			= Util.getString( mapCaseResult.get( 'orderNumber' ) );
		caseToUpsert.Origin 					= Util.getString( mapCaseResult.get( 'origin' ) );
		caseToUpsert.Subject 					= Util.getString( mapCaseResult.get( 'caseType' ) );
		caseToUpsert.Description 				= Util.getString( mapCaseResult.get( 'caseDescription' ) );

		upsert caseToUpsert LuizaCode__c;
		MktPlace_ProductInboundIntegrationBO.caseProduct( ( List<Object> ) mapCaseResult.get( 'products' ), caseToUpsert.LuizaCode__c );
	}

	/**
	*	Metodo principal de leitura e criação de um novo comentario no chamado 
	*	@param payload JSON com os dados de novo comentario
	*/
	public static void caseComment( String payload ) {
		Map<String, Object> mapResult = ( Map<String, Object> ) JSON.deserializeUntyped( payload );
        Map<String, Object> mapCommentResult = ( Map<String, Object> ) mapResult.get( 'commentCase' );
        
        String ticketNumber = Util.getString(mapCommentResult.get('idCase'));
        String authorType = Util.getString( mapCommentResult.get('authorType') );
        Boolean magMediation = 'true'.equalsIgnoreCase( Util.getString(mapCommentResult.get('magazineMediation')) );
		
		Account commentAuthor = AccountDAO.getAccountByLuizaCode( Util.getString(mapCommentResult.get( 'idAuthor' )) );
		Case caseToUpdate = CaseDAO.getCaseByLuizaCode( ticketNumber );
		
		if(caseToUpdate == null)
			throw new Utils.GenericException('O ticket número ' + ticketNumber + ' não foi encontrado');
        
		CaseComment__c caseCommentToInsert = new CaseComment__c();
		caseCommentToInsert.Autor__c 				= commentAuthor != null ? commentAuthor.Id : null;
		caseCommentToInsert.Caso__c 				= caseToUpdate.Id;
		caseCommentToInsert.Comentario__c 			= Util.getString( mapCommentResult.get('comment') );
		caseCommentToInsert.TipoAutor__c 			= Util.getAuthorType( authorType );
		caseCommentToInsert.MagazineMediation__c 	= magMediation;
		caseCommentToInsert.Private__c  			= Util.getBoolean( mapCommentResult.get('private') );

		CaseDAO.getInstance().insertData( caseCommentToInsert );
	}

}