src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>CNPJ__c</fullName>
        <label>CNPJ</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>LuizaCode__c</fullName>
        <externalId>true</externalId>
        <label>LuizaCode</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>NickName__c</fullName>
        <label>Nick Name</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>NomeFantasia__c</fullName>
        <label>Nome Fantasia</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SellerRating__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Avaliação Lojista</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TotalCases__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Número de Casos</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <recordTypes>
        <fullName>Conta_Negocio</fullName>
        <active>true</active>
        <label>Conta Negocio</label>
    </recordTypes>
    <recordTypes>
        <fullName>Seller</fullName>
        <active>true</active>
        <label>Lojista</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/AccountBuild.cls
@isTest
public class AccountBuild {
	
	public static Account createCustomerAcct(){
		return getNewAccount(
			'ClientePF',
			'José',
			'da Silva',
			'josedasilva@magazineluiza.com.br',
			'José da Silva',
			'0bee4889-99f6-43ec-8c88-13306f460f04',
			Utils.generateCpf()
		);
	}
	
	public static Account createSellerAcct(String cpfCnpj){
		return getNewAccount(
			'Seller',
			'Vtex',
			'',
			'',
			'',
			'sandboxtestes',
			cpfCnpj
		);
	}
	
	public static Account createMktPlaceAcct(){
		return getNewAccount(
			'Conta_Negocio',
			'magazineluiza',
			'',
			'teste@teste.com',
			'magazineluiza',
			'magazineluiza',
			Utils.generateCnpj()
		);
	}
	
	
	public static Account getNewAccount(String rtName, String firstName, String lastName, String email, String nickName, String luizaCode, String cpfCnpj){
		if('ClientePF'.equals(rtName)){
            return new Account(
            	RecordTypeId = Utils.getRecordTypeId('Account', 'ClientePF'),
                FirstName = firstName,
                LastName = lastName,
                Email__c = email,
                PersonMobilePhone = '11'+Utils.randomNumberAsString(8),
                NickName__c = nickName,
                LuizaCode__c = luizaCode,
                CPF_CNPJ__pc = cpfCnpj
            );
            
		} else {
            return new Account(
            	RecordTypeId = Utils.getRecordTypeId('Account', rtName),
                Name = firstName,
	            NomeFantasia__c = firstName + ' TestClass',
	            Email__c = email,
	            NickName__c = nickName,
                Description = 'testes',
                SellerRating__c = 244,
                TotalCases__c = 214,
                LuizaCode__c = luizaCode,
                CNPJ__c = cpfCnpj
            );
		}
        
	}
	
}