src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>CNPJ__c</fullName>
        <label>CNPJ</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LuizaCode__c</fullName>
        <externalId>true</externalId>
        <label>LuizaCode</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>NickName__c</fullName>
        <label>Nick Name</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>NomeFantasia__c</fullName>
        <label>Nome Fantasia</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>Seller</fullName>
        <active>true</active>
        <label>Lojista</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/MktPlace_InstanceToClassCoverage.cls
/*
	@autor Lincoln Soares
	@class Classe de Coberta
*/
public with sharing class MktPlace_InstanceToClassCoverage {
	
	//Create account record
	public static Account 	accountPerson(){
		return new Account(
			//	Name 				= 'Account Test Name',
			FirstName 			= 'Account', 
			LastName 	 		= 'Test Name',
			Phone 				= '1935621233',
			CNPJ__c 			= '45.880.281/0001-52',
			NickName__c			= 'NickName',
			LuizaCode__c		= 'abc12345',
			BillingStreet		= 'BStreet',
			BillingCity			= 'BCity',
			BillingState		= 'São Paulo',
			BillingPostalCode	= '12345-000',
			BillingCountry      = 'Brazil',
			ShippingStreet		= 'SStreet',
			ShippingCity		= 'SCity',
			ShippingState		= 'São Paulo',
			ShippingPostalCode	= '12345-000',
			ShippingCountry     = 'Brazil',
			RecordTypeId 		= 'RECORDTYPE_CLIENTE_PF'
			);
	}

	//Create account record
	public static Account 	accountCompany(){
		return new Account(
		    Name 				= 'Account Company Name',
			Phone 				= '1935621233',
			CNPJ__c 			= '45.880.281/0001-52',
			NomeFantasia__c     = 'Nome Fantasia Teste',
			NickName__c			= 'NickName',
			LuizaCode__c		= 'abc12345',
			BillingStreet		= 'BStreet',
			BillingCity			= 'BCity',
			BillingState		= 'São Paulo',
			BillingPostalCode	= '12345-000',
			BillingCountry      = 'Brazil',
			ShippingStreet		= 'SStreet',
			ShippingCity		= 'SCity',
			ShippingState		= 'São Paulo',
			ShippingPostalCode	= '12345-000',
			ShippingCountry     = 'Brazil',
			RecordTypeId 		= AccountDAO.RECORDTYPE_CLIENTE_PJ
			);
	}

	public static Account 	accountSeller(){
		return new Account(
		    Name 				= 'Account Seller Name',
			Phone 				= '1935621233',
			CNPJ__c 			= '45.880.281/0001-52',
			NomeFantasia__c     = 'Nome Fantasia Teste',
			NickName__c			= 'NickName',
			LuizaCode__c		= 'abc12345',
			BillingStreet		= 'BStreet',
			BillingCity			= 'BCity',
			BillingState		= 'São Paulo',
			BillingPostalCode	= '12345-000',
			BillingCountry      = 'Brazil',
			ShippingStreet		= 'SStreet',
			ShippingCity		= 'SCity',
			ShippingState		= 'São Paulo',
			ShippingPostalCode	= '12345-000',
			ShippingCountry     = 'Brazil',
			RecordTypeId 		= AccountDAO.RECORDTYPE_SELLER
			);
	}
}