src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>CNPJ__c</fullName>
        <label>CNPJ</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/AtivacaoApex__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>Ativo__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Ativo</label>
        <type>Checkbox</type>
    </fields>
    <label>AtivacaoApex</label>
</CustomObject>

src/classes/clsTestConta.cls
@isTest
public class clsTestConta {
    	
    static testMethod void TestConta(){
        
        AtivacaoApex__c at = new AtivacaoApex__c();
        at.Ativo__c = false;
        insert at;
        
        Account acc = new Account();
        	acc.CNPJ__c = '42.888.814/0001-54';
        	acc.Name = 'Teste';
        	acc.Type = 'Transportadora';
        insert acc;
        
        try{
        Account ac = new Account();
        	ac.CNPJ__c = '42.888.14/0001-54';
        	ac.Name = 'Teste2';
        	ac.Type = 'Transportadora';
        insert ac;
        }
        catch(Exception e)
        {
            
        }
        
        //Cliente cli = new Cliente();
              
    }
}