src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>LuizaCode__c</fullName>
        <externalId>true</externalId>
        <label>LuizaCode</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>LuizaCode__c</fullName>
        <externalId>true</externalId>
        <label>LuizaCode</label>
        <length>150</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>TotalSellerInteractions__c</fullName>
        <label>Total de interações Lojista</label>
        <summaryFilterItems>
            <field>CaseComment__c.TipoAutor__c</field>
            <operation>equals</operation>
            <value>Seller</value>
        </summaryFilterItems>
        <summaryForeignKey>CaseComment__c.Caso__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

src/objects/CaseComment__c.object
<CustomObject>
    <fields>
        <fullName>Autor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Autor</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>ComentariosCaso</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CancelamentoMagazine__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Cancelamento de pedido - Magazine</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Caso__c</fullName>
        <label>Caso</label>
        <referenceTo>Case</referenceTo>
        <relationshipName>ComentariosCaso</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Comentario__c</fullName>
        <label>Comentário</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Private__c</fullName>
        <defaultValue>true</defaultValue>
        <description>É uma mensagem para o logista?</description>
        <label>Mensagem para o logista</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>TipoAutor__c</fullName>
        <label>Tipo Autor</label>
        <picklist>
            <picklistValues>
                <fullName>Lojista</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cliente</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Magazine Luiza</fullName>
                <default>true</default>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Comentário do Caso</label>
    <nameField>
        <label>ID-Comentario</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Comentários do Caso</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/CaseCommentDAO.cls
/**
*    @author Diego Moreira
*    @class Classe DAO para objeto de comentario do caso
*/
public with sharing class CaseCommentDAO extends SObjectDAO {
	/*
		Singleton
    */  
	private static final CaseCommentDAO instance = new CaseCommentDAO();    
    private CaseCommentDAO(){}
    
    public static CaseCommentDAO getInstance() {
        return instance;
    }
    
    
    public static Map<Id, List<CaseComment__c>> getCaseCommentsMapByCaseId(Set<Id> caseIdSet){
        List<CaseComment__c> caseCommentList = getCaseCommentByCaseId(caseIdSet);
        Map<Id, List<CaseComment__c>> mapCommentsByCase = new Map<Id, List<CaseComment__c>>();
        
        for(Id i : caseIdSet){
            List<CaseComment__c> commentList = new List<CaseComment__c>();
            
            for(CaseComment__c cc : caseCommentList){
                if(cc.Caso__c == i) commentList.add(cc);
            }
            
            mapCommentsByCase.put(i, commentList);
        }
        
        return mapCommentsByCase;
    }
    
    
    public static List<CaseComment__c> getCaseCommentByCaseId(Set<Id> caseIdSet) {
        return [
            SELECT  Name,
                    Autor__c,
                    Autor__r.Name,
                    Caso__c,
                    Caso__r.TotalSellerInteractions__c,
                    Comentario__c,
                    TipoAutor__c,
                    Caso__r.LuizaCode__c,
                    Autor__r.LuizaCode__c,
                    Private__c,
                    CancelamentoMagazine__c
            
            FROM    CaseComment__c
            WHERE   Caso__c in :caseIdSet
        ];
    }

    /**
    *	Retorna os dados do comentario e de seus relacionamentos
    *	@param commentsId Id dos comentarios para consulta
    */
    public List<CaseComment__c> getCaseCommentById( List<String> commentsId ) {
    	return [SELECT Id, Name, Autor__c, Autor__r.Name, Caso__c, Caso__r.TotalSellerInteractions__c, Comentario__c, TipoAutor__c,
    			Caso__r.LuizaCode__c, Autor__r.LuizaCode__c, Private__c, CancelamentoMagazine__c
    				FROM CaseComment__c
    				WHERE Id in :commentsId];
    }
    
}