src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>LuizaCode__c</fullName>
        <externalId>true</externalId>
        <label>LuizaCode</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SellerRating__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Avaliação Lojista</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TotalCases__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Número de Casos</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>LuizaCode__c</fullName>
        <externalId>true</externalId>
        <label>LuizaCode</label>
        <length>150</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>MagazineDateMediation__c</fullName>
        <label>Data Mediação Magazine Luiza</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>MktPlaceBandeirinha__c</fullName>
        <label>Bandeirinha</label>
        <picklist>
            <picklistValues>
                <fullName>Vazio</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lojista</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cliente</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>OrderNumber__c</fullName>
        <label>Número do Pedido</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ProtocoloAtendimento__c</fullName>
        <label>Protocolo de atendimento</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Seller__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Lojista</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Casos (Logista)</relationshipLabel>
        <relationshipName>CasosSeller</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ServiceRating__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Nota do Atendimento</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

src/objects/CaseComment__c.object
<CustomObject>
    <fields>
        <fullName>Autor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Autor</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>ComentariosCaso</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Caso__c</fullName>
        <label>Caso</label>
        <referenceTo>Case</referenceTo>
        <relationshipName>ComentariosCaso</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Comentario__c</fullName>
        <label>Comentário</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>TipoAutor__c</fullName>
        <label>Tipo Autor</label>
        <picklist>
            <picklistValues>
                <fullName>Lojista</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cliente</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Magazine Luiza</fullName>
                <default>true</default>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Comentário do Caso</label>
    <nameField>
        <label>ID-Comentario</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Comentários do Caso</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/CaseProduct__c.object
<CustomObject>
    <fields>
        <fullName>Caso__c</fullName>
        <label>Caso</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Produtos do Caso</relationshipLabel>
        <relationshipName>ProdutosCaso</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Produto__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Produto</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Produtos do Caso</relationshipLabel>
        <relationshipName>ProdutosCaso</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Produto do Caso</label>
    <nameField>
        <label>Produto do Caso</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Produtos do Caso</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/CaseDAO.cls
/**
*    @author Diego Moreira
*    @class Classe de negocio de Caso
*/
public with sharing class CaseDAO extends SObjectDAO {
	/*
		Singleton
    */  
	private static final CaseDAO instance = new CaseDAO();    
    private CaseDAO(){}
    
    public static CaseDAO getInstance() {
        return instance;
    }
    
    public static final String RECORDTYPE_MKTPLACE_CANCELAMENTO_PEDIDO = Schema.SObjectType.Case.getRecordTypeInfosByName().get( 'MktPlace - Cancelamento' ).getRecordTypeId();
	public static final String RECORDTYPE_MKTPLACE_DUVIDA_PRODUTO = Schema.SObjectType.Case.getRecordTypeInfosByName().get( 'MktPlace - Dúvidas gerais' ).getRecordTypeId();
	public static final String RECORDTYPE_MKTPLACE_POSICAO_ENTREGA = Schema.SObjectType.Case.getRecordTypeInfosByName().get( 'MktPlace - Troca' ).getRecordTypeId();
    
    
    public static Map<Id, Case> getCaseMapById(Set<Id> caseIdSet){
        return new Map<Id, Case>( getCaseById(caseIdSet) );
    }
    
    /**
	*	Retorna os dados do caso 
	*	@param luizaCode id do caso para consulta de informações
    */
    public List<Case> getCaseByIntegrationId( String luizaCode ) {
        return [
            SELECT  Id,
                    LuizaCode__c,
                    Account.LuizaCode__c,
                    Status,
                    Seller__r.LuizaCode__c,
                    OrderNumber__c,
                    ProtocoloAtendimento__c,
                    RecordTypeId,
                    RecordType.Name,
                    (SELECT Id, Name, Autor__r.LuizaCode__c, Autor__r.Name, Comentario__c, TipoAutor__c, CreatedDate FROM ComentariosCaso__r),
                    (SELECT Id, Caso__r.LuizaCode__c, Produto__r.LuizaCode__c, Produto__r.Name, Produto__r.Description FROM ProdutosCaso__r)
            
            FROM    Case
            WHERE   LuizaCode__c = :luizaCode Limit 1
        ];
    }
    
    
    /**
    *   Retorna os dados do caso 
    *   @param luizaCode id do caso para consulta de informações
    */
    public static Case getCaseByLuizaCode( String luizaCode ) {
        List<Case> lstCase = [
            SELECT  RecordTypeId,
                    RecordType.Name,
                    LuizaCode__c,
                    Account.LuizaCode__c,
                    Status,
                    Seller__r.LuizaCode__c,
                    OrderNumber__c,
                    ProtocoloAtendimento__c,
                    MagazineDateMediation__c
                    
            FROM    Case
            WHERE   LuizaCode__c = :luizaCode 
            Limit 1
        ];
        
        return !lstCase.isEmpty() ? lstCase[0] : null;
    }


    /**
	*	Retorna os dados do caso 
	*	@param luizaCodes id do caso para consulta de informações
    */
    public List<Case> getCaseByIntegrationId( List<String> luizaCodes ) {
        return [
            SELECT  Id,
                    RecordTypeId,
                    RecordType.Name,
                    LuizaCode__c,
                    Account.LuizaCode__c,
                    Seller__c,
                    Seller__r.SellerRating__c,
                    Seller__r.LuizaCode__c,
                    OrderNumber__c,
                    ProtocoloAtendimento__c,
                    Description,
                    ServiceRating__c,
                    Seller__r.TotalCases__c,
                    (SELECT Id, Name, Autor__r.LuizaCode__c, Autor__r.Name, Comentario__c, TipoAutor__c, CreatedDate FROM ComentariosCaso__r),
                    (SELECT Id, Caso__r.LuizaCode__c, Produto__r.LuizaCode__c, Produto__r.Name, Produto__r.Description FROM ProdutosCaso__r)
            
            FROM    Case
            WHERE   LuizaCode__c in :luizaCodes
        ];
    }

    /**
    *
    *
    */
    public List<Case> getCaseById( List<String> caseId ) {
        return [
            SELECT  Id,
                    LuizaCode__c,
                    Account.LuizaCode__c,
                    Seller__c,
                    Seller__r.SellerRating__c,
                    Seller__r.LuizaCode__c,
                    OrderNumber__c,
                    ProtocoloAtendimento__c,
                    Description,
                    RecordTypeId,
                    RecordType.Name,
                    Status,
                    IsClosed
            
            FROM    Case
            WHERE   Id in :caseId
        ];
    }

    /**
    *
    *
    */
    public static List<Case> getCaseById(Set<Id> caseIdSet) {
        return [
            SELECT  Id,
                    LuizaCode__c,
                    Account.LuizaCode__c,
                    Seller__c,
                    Seller__r.SellerRating__c,
                    Seller__r.LuizaCode__c,
                    OrderNumber__c,
                    ProtocoloAtendimento__c,
                    Description,
                    RecordTypeId,
                    RecordType.Name,
                    Status,
                    IsClosed,
                    MagazineDateMediation__c,
                    MktPlaceBandeirinha__c
            
            FROM    Case
            WHERE   Id in :caseIdSet
        ];
    }

}