src/objects/CaseResolution__c.object
<CustomObject>
    <fields>
        <fullName>Area_solucionadora__c</fullName>
        <label>Área solucionadora</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Caso__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Caso</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Resoluções</relationshipLabel>
        <relationshipName>Resolu_es_de_Casos</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Data_de_Inicio__c</fullName>
        <label>Data de Inicio</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Formulario_Preenchido__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Formulário Preenchido</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Status_Resolucao__c</fullName>
        <label>Status Resolução</label>
        <picklist>
            <picklistValues>
                <fullName>Em tratativa</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Em fila</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fechado</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Resolução de Caso</label>
    <nameField>
        <displayFormat>RC-{000}</displayFormat>
        <label>Número da Resolução</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Resoluções de Casos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/clsTestMetodosUteis.cls
@isTest(seealldata=true)
public with sharing class clsTestMetodosUteis {

	static testMethod void testaMetodos()
	{
		clsMetodosUteis metUteis = new clsMetodosUteis();
        metUteis.RetornaEstado('TO');
        String cpf = metUteis.formataCPFCNPJ('14725836900');
        String cnpj = metUteis.formataCPFCNPJ('14251436000111');
        metUteis.ValidarEmail('filipe.marino.teste.com.br');
        metUteis.ValidarEmail('filipe.marino@teste.com.br');
        metUteis.ajustaTelefone('01121414005');
        metUteis.ajustaTelefone('1121414005');
        metUteis.ajustaTelefone('121414005');
        metUteis.ajustaTelefone('21414005');
        metUteis.ajustaTelefone('1414005');
        metUteis.validaCpfCnpj('678.463.461-64');
        metUteis.validaCpfCnpj('678.463.666-64');
        metUteis.validaCpfCnpj('86.728.632/0001-91');
        metUteis.validaCpfCnpj('86.728.999/0001-91');
        metUteis.formataCPFCNPJ('86.728.999/0001-91');
        String dt=clsMetodosUteis.RetornaDiaUtil(1);
        String acento = metUteis.RemoverAcentos('País');
        String dtUtil = clsMetodosUteis.RetornaDiaUtil(2,System.now());
        List<CaseResolution__c> CR = [Select id,area_solucionadora__c,ownerid,Status_Resolucao__c,Formulario_Preenchido__c,data_de_inicio__c from CaseResolution__c where Formulario_Preenchido__c=false and Caso__c != null limit 2];
        clsMetodosUteis.AtualizaProprietariosCaseResolution(CR,'005j000000C0QIy',String.valueof(cr[0].ownerid),'Em tratativa');
        List<Task> objTarefa = [Select id,area_solucionadora__c,ownerid,status,Tarefa_Respondida__c,data_de_inicio__c,Subject from Task where Tarefa_Respondida__c=false and subject like '%Contatar%' limit 2];
        clsMetodosUteis.AtualizaProprietariosTask(objTarefa, '005j000000C0QIy', String.valueof(cr[0].ownerid), 'Em tratativa');
	} 
}