src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>LuizaCode__c</fullName>
        <externalId>true</externalId>
        <label>LuizaCode</label>
        <length>150</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

src/objects/CaseProduct__c.object
<CustomObject>
    <fields>
        <fullName>Caso__c</fullName>
        <label>Caso</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Produtos do Caso</relationshipLabel>
        <relationshipName>ProdutosCaso</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Produto__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Produto</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Produtos do Caso</relationshipLabel>
        <relationshipName>ProdutosCaso</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Produto do Caso</label>
    <nameField>
        <label>Produto do Caso</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Produtos do Caso</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>LuizaCode__c</fullName>
        <externalId>true</externalId>
        <label>LuizaCode</label>
        <length>150</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
</CustomObject>

src/classes/MktPlace_ProductInboundIntegrationBO.cls
/**
*	@author Diego Moreira
*	@class Classe de negocio para leitura do dados de integração 
*/
public class MktPlace_ProductInboundIntegrationBO {
	/**
	* 	Cria os dados do produto do caso 
	*	@param objProductList Lista de objeto contendo os atributos do produto
	*/
	public static void caseProduct( List<Object> objProductList, String idCase ) {
		List<CaseProduct__c> caseProductToInsert = new List<CaseProduct__c>();

		for( Object objResult : objProductList ) {
            Map<String, Object> mapProduct = ( Map<String, Object> ) objResult;

            CaseProduct__c caseProduct = new CaseProduct__c();
            caseProduct.Caso__r 	= new Case( LuizaCode__c = idCase );
            caseProduct.Produto__r 	= new Product2( LuizaCode__c = Util.getString( mapProduct.get( 'productId' ) ) );

            caseProductToInsert.add( caseProduct );
        }

        insert caseProductToInsert;
	}		

	/**
	* 	Cria/Atualiza os dados do produto 
	*	@param objProductList Lista de objeto contendo os atributos do produto
	*/
	public static void product( List<Object> objProductList ) {
		List<Product2> productToUpsert = new List<Product2>();

		for( Object objResult : objProductList ) {
            Map<String, Object> mapProduct = ( Map<String, Object> ) objResult;

            Product2 product = new Product2();
            product.LuizaCode__c 	= Util.getString( mapProduct.get( 'productId' ) );
            product.Name 			= Util.getString( mapProduct.get( 'productName' ) );
            product.Description 	= Util.getString( mapProduct.get( 'productDescription' ) );
            product.IsActive 		= true;

            productToUpsert.add( product );
        }

        upsert productToUpsert LuizaCode__c;
	}
}