src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>ContactSeller__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contato do Lojista</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Casos (Contato do Lojista)</relationshipLabel>
        <relationshipName>ContatoSeller</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>LuizaCode__c</fullName>
        <externalId>true</externalId>
        <label>LuizaCode</label>
        <length>150</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>OrderNumber__c</fullName>
        <label>Número do Pedido</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ProtocoloAtendimento__c</fullName>
        <label>Protocolo de atendimento</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Seller__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Lojista</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Casos (Logista)</relationshipLabel>
        <relationshipName>CasosSeller</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

src/classes/CaseBuild.cls
@isTest
public class CaseBuild {
	
	public static Case createCase(String rtName, Id sellerId, Id contactSellerId, String orderNumber, String protocolNumb){
		return getNewCase(rtName, sellerId, contactSellerId, orderNumber, protocolNumb);
	}
	
	public static Case createCase(String rtName, Id sellerId, Id contactSellerId){
		String randomOrderNumber = Utils.randomNumberAsString(16);
		String randomProtocol = String.valueOf(Datetime.now().year())+Utils.randomNumberAsString(12);
		return getNewCase(rtName, sellerId, contactSellerId, randomOrderNumber, randomProtocol);
	}
	
	
	public static Case getNewCase(String rtName, Id sellerId, Id contactSellerId, String orderNumber, String protocolNumb){
		return new Case(
			RecordTypeId = Utils.getRecordTypeId('Case', rtName),
			Subject = 'Teste',
			Description = 'Caso de testes Marketplace',
			Seller__c = sellerId,
			ContactSeller__c = contactSellerId,
			OrderNumber__c = orderNumber,
			ProtocoloAtendimento__c = protocolNumb,
			LuizaCode__c = protocolNumb
		);
	}
	
}