src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>MagazineMediation__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Mediação Magazine Luiza?</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

src/objects/CaseComment__c.object
<CustomObject>
    <fields>
        <fullName>CancelamentoMagazine__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Cancelamento de pedido - Magazine</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>MagazineMediation__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Precisa da mediação do Magazine?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Private__c</fullName>
        <defaultValue>true</defaultValue>
        <description>É uma mensagem para o logista?</description>
        <label>Mensagem para o logista</label>
        <type>Checkbox</type>
    </fields>
    <label>Comentário do Caso</label>
    <nameField>
        <label>ID-Comentario</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Comentários do Caso</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Queue__c.object
<CustomObject>
    <fields>
        <fullName>EventName__c</fullName>
        <label>Event name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Payload__c</fullName>
        <label>Payload</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <label>Queue</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Queue</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Queues</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/MktPlace_GibaIntegrationServiceTest.cls
@isTest(SeeAllData=true)
private class MktPlace_GibaIntegrationServiceTest {
	@isTest static void testGibaIntegrationComment() { 
		CaseComment__c comment = new CaseComment__c();
		comment.MagazineMediation__c 	= true;
		comment.Private__c  			= true;
		comment.CancelamentoMagazine__c	= true;

		String jsonResult = MktPlace_CaseOutboundIntegrationBO.getJsonComment( comment );

        Test.setMock( HttpCalloutMock.class, new MktPlace_GibaIntegrationServiceMock() );
        
        Queue__c queue = QueueBO.getInstance().createQueue( QueueEventNames.MKTPLACE_CASE_COMMENT_SALESFORCE_TO_GIBA.name(), jsonResult, false );
        Database.insert(queue);
        
        MktPlace_CaseOutboundIntegrationBO.executeQueue( queue.Id, queue.EventName__c, queue.Payload__c );
    }

    @isTest static void testGibaIntegrationCommentError() { 
        CaseComment__c comment = new CaseComment__c();
        comment.MagazineMediation__c    = true;
        comment.Private__c              = true;
        comment.CancelamentoMagazine__c = true;

        String jsonResult = MktPlace_CaseOutboundIntegrationBO.getJsonComment( comment );

        Test.setMock( HttpCalloutMock.class, new MktPlace_GibaIntegrationServiceMock() );
        
        Queue__c queue = QueueBO.getInstance().createQueue( QueueEventNames.MKTPLACE_CASE_COMMENT_SALESFORCE_TO_GIBA.name(), jsonResult, false );
        Database.insert(queue);

        MktPlace_CaseOutboundIntegrationBO.executeQueue( queue.Id, queue.EventName__c, queue.Payload__c );
    }

    @isTest static void testGibaIntegrationClose() { 
		Case caseResult = new Case();

		String jsonResult = MktPlace_CaseOutboundIntegrationBO.getJsonClose( caseResult );

        Test.setMock( HttpCalloutMock.class, new MktPlace_GibaIntegrationServiceMock() );        

        Queue__c queue = QueueBO.getInstance().createQueue( QueueEventNames.MKTPLACE_CASE_COMMENT_SALESFORCE_TO_GIBA.name(), jsonResult, false );
        Database.insert(queue);

        MktPlace_CaseOutboundIntegrationBO.executeQueue( queue.Id, queue.EventName__c, queue.Payload__c );
    }
}