src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>AreaCausingException__c</fullName>
        <label>Área causadora da exceção</label>
        <picklist>
            <picklistValues>
                <fullName>Atendimento</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cliente</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Controle de Estoque</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fornecedor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Processamento</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Reversa</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Televendas</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Transportes (PREENCHER O &quot;Bloco 3&quot; - Transportes)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Transportes (PREENCHER &quot;Bloco 2&quot;)</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>CustomerWinsBrandModel__c</fullName>
        <label>Cliente possui alguma preferência ?</label>
        <picklist>
            <picklistValues>
                <fullName>Sim</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Não</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Level_1__c</fullName>
        <label>Classificação</label>
        <picklist>
            <picklistValues>
                <fullName>Análise do Produto</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cadastro e seu espaço</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelamento</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Coleta e devolução</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Entrega com nota fiscal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Garantia estendida</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Nota Fiscal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Troca</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Entrega sem nota fiscal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Casos abertos pelo CD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>E-mail</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ligação</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Level_2__c</fullName>
        <label>Motivo do Contato</label>
        <picklist>
            <controllingField>Level_1__c</controllingField>
            <picklistValues>
                <fullName>Análise do Produto - Faltando acessórios</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Produto diferente do que constava no site</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Produto com preço | Forma de pagamento diferente do ato da compra</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Erro em promoção anunciada</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Problemas com o cadastro no site</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Informação de produto</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Informação de Cadastro</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Informação de cancelamento - procedimento e prazos</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Informação sobre a coleta / devolução</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Recontato com protocolo aberto ou dentro do prazo de coleta</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Informação de entrega procecimento e prazos</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Recontato com protocolo aberto ou dentro do prazo de entrega</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Informação de entrega procedimento e prazos</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Informação de garantia estendida</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Informações sobre notas fiscais / DANFE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Informação de troca - procedimento e prazos</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Solicitar similiar para troca</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Atraso - Pedido liberado faturamento - Não tem produto disponível</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Atraso - Pedido não liberado faturamento</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Atraso - Pedido liberado faturamento - Tem produto disponível</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Há item do pedido que não foi processado</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Boleto com código inválido</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pagamento do pedido não foi confirmado</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Abertura de cancelamento ADM ou ML Admin</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dados para restituição de cancelamento ML Admin</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Reclamação de atraso na restituição ou estorno</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Solicitação de cancelamento em exceção</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Solicitar alteração no status restituição ou estorno</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Solicitar cancelamento de pedido liberado para faturamento</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Alterar endereço de coleta</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Produto devolvido ao CD</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>PaymentForm__c</fullName>
        <label>Forma de pagamento</label>
        <picklist>
            <picklistValues>
                <fullName>Cartão</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Boleto (PREENCHER O &quot;Bloco 2&quot; - Boleto)</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>ProblemTypeRegistration__c</fullName>
        <label>Tipo de problema com o cadastro</label>
        <picklist>
            <picklistValues>
                <fullName>Cliente não consegue modificar a senha (NÃO PREENCHER NOVO E-MAIL)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cliente não consegue modificar o e-mail</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cliente não acessa mais e-mail e deseja alterar</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>ProposedSolutionCommercialSupport__c</fullName>
        <label>Solução proposta pelo suporte comercial</label>
        <picklist>
            <picklistValues>
                <fullName>Fornecedor enviará peça ou acessório</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Não temos produto correto disponível e nem similar - Orientar cliente a escolher outro</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Efetue a troca para o cliente pelo produto correto (&quot;Bloco 2&quot;: PREENCHER A PERGUNTA 1)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Previsão de recebimento do item (&quot;Bloco 2&quot;: PREENCHER AS PERGUNTAS 2., 3. E 4.)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Indisponível no fornecedor/ Fora de linha (&quot;Bloco 2&quot;: PREENCHER AS PERGUNTAS DE 3. A 8.)</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>ReasonException__c</fullName>
        <label>Motivo que ocasionou a exceção?</label>
        <picklist>
            <picklistValues>
                <fullName>Atraso interno Reversa / Atraso envio RCV</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Atraso interno Reversa / Atraso na análise do produto</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Atraso interno Reversa / Atraso na Emissão de NFE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Atraso interno Reversa / Atraso na re-postagem</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Avaria - após 48 horas da entrega</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Avaria - consta no status - pedido ainda não foi entregue</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Avaria dentro de 48 horas da entrega</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cliente não aceita o prazo / processos normais</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Coleta - Devolução atrasada com comprovante (&quot;Bloco 3&quot; - Transportes: PREENCHER 2. E 4.)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Coleta - Devolução atrasada sem comprovante / transportadora alega não ter coletado (&quot;Bloco 3&quot; - Transportes: PREENCHER 2. E 4.)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Coleta - Devolução atrasada sem comprovante / transportadora não confirmou a coleta (&quot;Bloco 3&quot; - Transportes: PREENCHER 2. E 4.)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Coleta - Recontato (&quot;Bloco 3&quot; - Transportes: PREENCHER 3. E 4.)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Divergência de estoque</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Embalagem interna com dados de outro cliente (PREENCHER &quot;Bloco 4&quot;)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Erro no ato da compra</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Extravio - consta no status - pedido ainda não foi entregue</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Operacional Processamento / Atraso na emissão da troca</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Operacional Processamento / Envio produto errado</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Operacional Processamento / Falta um item</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pedido faltando item</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Produto indisponível</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sinistro - consta no status - pedido ainda não foi entregue</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Coleta - Devolução atrasada com comprovante (&quot;Bloco 2&quot; - Transportes: PREENCHER 2. E 4.)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Coleta - Devolução atrasada sem comprovante / transportadora alega não ter coletado (&quot;Bloco 2&quot; - Transportes: PREENCHER 2. E 4.)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Coleta - Devolução atrasada sem comprovante / transportadora não confirmou a coleta (&quot;Bloco 2&quot; - Transportes: PREENCHER 2. E 4.)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Coleta - Recontato (&quot;Bloco 2&quot; - Transportes: PREENCHER 3. E 4.)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Embalagem interna com dados de outro cliente (PREENCHER &quot;Bloco 3&quot;)</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>StopShippingProduct__c</fullName>
        <label>Barrar envio do produto?</label>
        <picklist>
            <picklistValues>
                <fullName>Sim</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Não (PREENCHER ENDEREÇO - próxima pergunta)</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>ThereDifferenceCharged__c</fullName>
        <label>Há diferença a ser cobrada</label>
        <picklist>
            <picklistValues>
                <fullName>Sim (PREENCHER VALOR DA DIFERENÇA - próxima pergunta)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Não</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>TypeDelevery__c</fullName>
        <label>Tipo de entrega</label>
        <picklist>
            <picklistValues>
                <fullName>Agendada</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Convencional</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Agendada (PREENCHER DATA DO AGENDAMENTO - próxima pergunta)</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <recordTypes>
        <fullName>Coleta</fullName>
        <active>true</active>
        <businessProcess>Magazine Luiza</businessProcess>
        <label>Coleta</label>
    </recordTypes>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

src/classes/clsTestCase.cls
@isTest
public with sharing class clsTestCase {

    static testMethod void TestCase() {
        Case cs = new Case();
        cs.Origin = 'E-Mail (S/Tratativa)';
        cs.Level_1__c='Casos abertos pelo CD';
        cs.Level_2__c='Produto devolvido ao CD';
        insert cs;
        cs.Origin = 'E-Mail (S/Tratativa)';
        cs.Level_1__c='Casos abertos pelo CD';
        cs.Level_2__c='Produto devolvido ao CD';
        cs.Subject='Teste';
        update cs;
        
        
    }
    
    private static Case cs = new Case();
    
    static {
        Case cs = new Case();
        cs.Origin = 'Telefone';
        cs.Level_1__c='Casos abertos pelo CD';
        cs.Level_2__c='Produto devolvido ao CD';
        insert cs;
    }
    
    
    static testMethod void TestCaseValidacao01(){
        Test.startTest();
        
        try {
            cs.PaymentForm__c = 'Boleto (PREENCHER O Bloco 2 - Boleto';
            update cs;
        } catch(Exception ex) {
        
        }
        
        Test.stopTest();
    }
    
    static testMethod void TestCaseValidacao02(){
        Test.startTest();
        
        try {
            cs.PaymentForm__c = '';
            cs.AreaCausingException__c='Transportes (PREENCHER O "Bloco 3" - Transportes)';
            update cs;
        } catch(Exception ex) {
        
        }
        
        Test.stopTest();
    }
    
    static testMethod void TestCaseValidacao03(){
        Test.startTest();
        
        try {
            cs.PaymentForm__c = '';
            cs.AreaCausingException__c='';
            cs.ReasonException__c='Coleta - Devolução atrasada com comprovante ("Bloco 3" - Transportes: PREENCHER 2. E 4.)';
            update cs;
        } catch(Exception ex) {
        
        }
        
        Test.stopTest();
    }
    
    static testMethod void TestCaseValidacao04(){
        Test.startTest();
        
        try {
            cs.PaymentForm__c = '';
            cs.AreaCausingException__c='';
            cs.ReasonException__c='Coleta - Recontato ("Bloco 3" - Transportes: PREENCHER 3. E 4.)';
            update cs;
        } catch(Exception ex) {
        
        }
        
        Test.stopTest();
    }
    
    static testMethod void TestCaseValidacao05(){
        Test.startTest();
        
        try {
            cs.PaymentForm__c = '';
            cs.AreaCausingException__c='';
            cs.ReasonException__c='Embalagem interna com dados de outro cliente (PREENCHER "Bloco 4")';
            update cs;
        } catch(Exception ex) {
        
        }
        
        Test.stopTest();
    }
    
    static testMethod void TestCaseValidacao06(){
        Test.startTest();
        
        try {
            cs.PaymentForm__c = '';
            cs.AreaCausingException__c='';
            cs.ReasonException__c='';
            cs.ProblemTypeRegistration__c='Cliente não consegue modificar a senha (NÃO PREENCHER NOVO E-MAIL)';
            update cs;
        } catch(Exception ex) {
        
        }
        
        Test.stopTest();
    }
    
    static testMethod void TestCaseValidacao07(){
        Test.startTest();
        
        try {
            cs.PaymentForm__c = '';
            cs.AreaCausingException__c='';
            cs.ReasonException__c='';
            cs.ProblemTypeRegistration__c='Cliente não consegue modificar a senha (NÃO PREENCHER NOVO E-MAIL)';
            update cs;
        } catch(Exception ex) {
        
        }
        
        Test.stopTest();
    }
    
    static testMethod void TestCaseValidacao08(){
        Test.startTest();
        
        try {
            cs.PaymentForm__c = '';
            cs.AreaCausingException__c='';
            cs.ReasonException__c='';
            cs.ProblemTypeRegistration__c='Cliente não consegue modificar a senha (NÃO PREENCHER NOVO E-MAIL)';
            update cs;
        } catch(Exception ex) {
        
        }
        
        Test.stopTest();
    }
    
    static testMethod void TestCaseValidacao09(){
        Test.startTest();
        
        try {
            cs.PaymentForm__c = '';
            cs.AreaCausingException__c='';
            cs.ReasonException__c='';
            cs.ProblemTypeRegistration__c='';
            cs.TypeDelevery__c='Agendada (PREENCHER DATA DO AGENDAMENTO - próxima pergunta)';
            update cs;
        } catch(Exception ex) {
        
        }
        
        Test.stopTest();
    }
    
    static testMethod void TestCaseValidacao10(){
        Test.startTest();
        
        try {
            cs.PaymentForm__c = '';
            cs.AreaCausingException__c='';
            cs.ReasonException__c='';
            cs.ProblemTypeRegistration__c='';
            cs.TypeDelevery__c='';
            cs.CustomerWinsBrandModel__c='Sim (PREENCHER PREFERÊNCIA DO CLIENTE - próxima pergunta)';
            update cs;
        } catch(Exception ex) {
        
        }
        
        Test.stopTest();
    }
    
    static testMethod void TestCaseValidacao11(){
        Test.startTest();
        
        try {
            cs.PaymentForm__c = '';
            cs.AreaCausingException__c='';
            cs.ReasonException__c='';
            cs.ProblemTypeRegistration__c='';
            cs.TypeDelevery__c='';
            cs.CustomerWinsBrandModel__c='';
            cs.ThereDifferenceCharged__c='Sim (PREENCHER VALOR DA DIFERENÇA - próxima pergunta)';
            update cs;
        } catch(Exception ex) {
        
        }
        
        Test.stopTest();
    }
    
    static testMethod void TestCaseValidacao12(){
        Test.startTest();
        
        try {
            cs.PaymentForm__c = '';
            cs.AreaCausingException__c='';
            cs.ReasonException__c='';
            cs.ProblemTypeRegistration__c='';
            cs.TypeDelevery__c='';
            cs.CustomerWinsBrandModel__c='';
            cs.ThereDifferenceCharged__c='';
            cs.ProposedSolutionCommercialSupport__c='Efetue a troca para o cliente pelo produto correto ("Bloco 2": PREENCHER A PERGUNTA 1)';
            update cs;
        } catch(Exception ex) {
        
        }
        
        Test.stopTest();
    }
    
    static testMethod void TestCaseValidacao13(){
        Test.startTest();
        
        try {
            cs.PaymentForm__c = '';
            cs.AreaCausingException__c='';
            cs.ReasonException__c='';
            cs.ProblemTypeRegistration__c='';
            cs.TypeDelevery__c='';
            cs.CustomerWinsBrandModel__c='';
            cs.ThereDifferenceCharged__c='';
            cs.ProposedSolutionCommercialSupport__c='Previsão de recebimento do item ("Bloco 2": PREENCHER AS PERGUNTAS 2., 3. E 4.)';
            update cs;
        } catch(Exception ex) {
        
        }
        
        Test.stopTest();
    }
    
    static testMethod void TestCaseValidacao14(){
        Test.startTest();
        
        try {
            cs.PaymentForm__c = '';
            cs.AreaCausingException__c='';
            cs.ReasonException__c='';
            cs.ProblemTypeRegistration__c='';
            cs.TypeDelevery__c='';
            cs.CustomerWinsBrandModel__c='';
            cs.ThereDifferenceCharged__c='';
            cs.ProposedSolutionCommercialSupport__c='Indisponível no fornecedor/ Fora de linha ("Bloco 2": PREENCHER AS PERGUNTAS DE 3. A 8.)';
            update cs;
        } catch(Exception ex) {
        
        }
        
        Test.stopTest();
    }
    
    static testMethod void TestCaseValidacao15(){
        Test.startTest();
        
        try {
            cs.PaymentForm__c = '';
            cs.AreaCausingException__c='';
            cs.ReasonException__c='';
            cs.ProblemTypeRegistration__c='';
            cs.TypeDelevery__c='';
            cs.CustomerWinsBrandModel__c='';
            cs.ThereDifferenceCharged__c='';
            cs.ProposedSolutionCommercialSupport__c='';
            cs.StopShippingProduct__c='Não (PREENCHER ENDEREÇO - próxima pergunta)';
            update cs;
        } catch(Exception ex) {
        
        }
        
        Test.stopTest();
    }
    
    static testMethod void TestCaseValidacao16(){
        Test.startTest();
        
        try {
            cs.PaymentForm__c = '';
            cs.AreaCausingException__c='';
            cs.ReasonException__c='';
            cs.ProblemTypeRegistration__c='';
            cs.TypeDelevery__c='';
            cs.CustomerWinsBrandModel__c='';
            cs.ThereDifferenceCharged__c='';
            cs.ProposedSolutionCommercialSupport__c='';
            cs.StopShippingProduct__c='';
            cs.TypeNFRecharged__c='Coleta (PREENCHER Número NF Coleta)';
            update cs;
        } catch(Exception ex) {
        
        }
        
        Test.stopTest();
    }
    
}