src/objects/CaseResolution__c.object
<CustomObject>
    <fields>
        <fullName>Area_solucionadora__c</fullName>
        <label>Área solucionadora</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Caso__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Caso</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Resoluções</relationshipLabel>
        <relationshipName>Resolu_es_de_Casos</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Data_de_Inicio__c</fullName>
        <label>Data de Inicio</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Formulario_Preenchido__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Formulário Preenchido</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Status_Resolucao__c</fullName>
        <label>Status Resolução</label>
        <picklist>
            <picklistValues>
                <fullName>Em tratativa</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Em fila</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fechado</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Resolução de Caso</label>
    <nameField>
        <displayFormat>RC-{000}</displayFormat>
        <label>Número da Resolução</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Resoluções de Casos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/CaseResolutionDAO.cls
public class CaseResolutionDAO {
	
	public static Map<Id, List<CaseResolution__c>> getCaseResolutionsMapByCaseId(Set<Id> caseIdSet){
		Map<Id, List<CaseResolution__c>> mapResolutions = new Map<Id, List<CaseResolution__c>>();
		List<CaseResolution__c> caseResolutionList = getCaseResolutionsByCaseId(caseIdSet);
		
		for(Id i : caseIdSet){
			List<CaseResolution__c> caseResList = new List<CaseResolution__c>();
			
			for(CaseResolution__c res : caseResolutionList){
				if(res.Caso__c == i)
					caseResList.add(res);
			}
			
			mapResolutions.put(i, caseResList);
		}
		
		return mapResolutions;
	}
	
	public static List<CaseResolution__c> getCaseResolutionsByCaseId(Set<Id> caseIdSet){
		return [
            SELECT 	Id,
		            Area_solucionadora__c,
		            OwnerId,
		            Status_Resolucao__c,
		            Formulario_Preenchido__c,
		            Data_de_Inicio__c,
		            Caso__c
		            
            FROM 	CaseResolution__c
            WHERE 	Caso__c in :caseIdSet
            AND 	Formulario_Preenchido__c = false
        ];
	}
	
}