src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>MagazineDateMediation__c</fullName>
        <label>Data Mediação Magazine Luiza</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>MagazineMediation__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Mediação Magazine Luiza?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>MktPlaceBandeirinha__c</fullName>
        <label>Bandeirinha</label>
        <picklist>
            <picklistValues>
                <fullName>Vazio</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lojista</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cliente</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

src/objects/CaseComment__c.object
<CustomObject>
    <fields>
        <fullName>Autor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Autor</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>ComentariosCaso</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Caso__c</fullName>
        <label>Caso</label>
        <referenceTo>Case</referenceTo>
        <relationshipName>ComentariosCaso</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Comentario__c</fullName>
        <label>Comentário</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>MagazineMediation__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Precisa da mediação do Magazine?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Private__c</fullName>
        <defaultValue>true</defaultValue>
        <description>É uma mensagem para o logista?</description>
        <label>Mensagem para o logista</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>TipoAutor__c</fullName>
        <label>Tipo Autor</label>
        <picklist>
            <picklistValues>
                <fullName>Lojista</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cliente</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Magazine Luiza</fullName>
                <default>true</default>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Comentário do Caso</label>
    <nameField>
        <label>ID-Comentario</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Comentários do Caso</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Queue__c.object
<CustomObject>
    <label>Queue</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Queue</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Queues</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/CaseCommentBO.cls
/**
*	@author Diego Moreira
*	@class Classe de negocio para o objeto de comentario do caso
*/
public with sharing class CaseCommentBO {
	/*
        Singleton
    */
    private static final CaseCommentBO instance = new CaseCommentBO();
    private CaseCommentBO(){}
    
    public static CaseCommentBO getInstance() {
        return instance;
    }
    
    /**
    *	Replica os comentarios para a estrutura de comentarios padrões do SF
    *	@param newComments Lista de novos comentarios adicionados
    */
    public void replicaNovoComentario( List<CaseComment__c> newComments ) {
    	List<CaseComment> commentsToInsert = new List<CaseComment>();
    	List<String> commentsId = new List<String>();
        
    	for( CaseComment__c comment : newComments )
    		commentsId.add( comment.Id );
            
    	for( CaseComment__c comment : CaseCommentDAO.getInstance().getCaseCommentById( commentsId ) ) {
    		commentsToInsert.add( new CaseComment( 
    			ParentId = comment.Caso__c, 
    			CommentBody = comment.Autor__r.Name + ' (' + comment.TipoAutor__c + ') - ' +  comment.Comentario__c 
			) );
    	}
        
    	insert commentsToInsert;
    }
    
    /**
    *   Cria integração de saida de novo comentario
    *   @param newComments Lista de novos comentarios adicionados
    */
    public void criaFilaIntegracao( List<CaseComment__c> newComments ) {
        List<String> commentsId = new List<String>();
        List<String> jsonList = new List<String>();
        List<Queue__c> queueListInsert = new List<Queue__c>();
        
        for( CaseComment__c comment : newComments ) {
            if( comment.TipoAutor__c.equals( 'Magazine Luiza' ) )
                commentsId.add( comment.Id );
        }
        
        for( CaseComment__c comment : CaseCommentDAO.getInstance().getCaseCommentById( commentsId ) ) {
            jsonList.add( MktPlace_CaseOutboundIntegrationBO.getJsonComment( comment ) );
        }
        
        for( String jsonResult : jsonList ) {
            queueListInsert.add( QueueBO.getInstance().createQueue( QueueEventNames.MKTPLACE_CASE_COMMENT_SALESFORCE_TO_GIBA.name(), jsonResult, false ) );    
        }
        
        Database.insert(queueListInsert);
    }
    
    public static void setMktPlaceStatusBandeirinha(List<CaseComment__c> triggerNew){
        Set<Id> caseIdSet = SetUtils.getCaseCommentCaseIdSet(triggerNew);
        Map<Id, Case> caseMap = CaseDAO.getCaseMapById( caseIdSet );
        List<Case> listCaseUpdate = new List<Case>();
        
        for(CaseComment__c cc : triggerNew){
            if(!caseMap.containsKey(cc.Caso__c)) continue;
            Case commentCase = caseMap.get(cc.Caso__c);
            Boolean underMediation = cc.MagazineMediation__c || commentCase.MagazineDateMediation__c != null;
            Boolean isCustomer = 'Cliente'.equalsIgnoreCase(cc.TipoAutor__c);
            Boolean isSeller = 'Lojista'.equalsIgnoreCase(cc.TipoAutor__c);
            Boolean isMagazine = 'Magazine Luiza'.equalsIgnoreCase(cc.TipoAutor__c);
            String caseBandeirinha;
            String caseStatus;
            
            // Se é comentário privado
            if(cc.Private__c) {
                System.debug('@@@ isPrivate cc.TipoAutor__c: ' + cc.TipoAutor__c);
                caseStatus = commentCase.Status;
                
                if(isSeller) {
                    caseBandeirinha = 'Lojista';
                    
                } else if(isMagazine) {
                    caseBandeirinha = 'Vazio';
                }
                
            } else if(underMediation) { // Se é um comentário sob mediação magazine
                System.debug('@@@ underMediation cc.TipoAutor__c: ' + cc.TipoAutor__c);
                
                if(isCustomer) {
                    caseStatus = 'Aguardando resposta do Magazine Luiza';
                    caseBandeirinha = 'Cliente';
                    
                } else if(isMagazine) {
                    caseStatus = 'Aguardando resposta do Cliente';
                    caseBandeirinha = 'Vazio';
                }
                
            } else { // Se não está sob mediação magazine
                System.debug('@@@ else cc.TipoAutor__c: ' + cc.TipoAutor__c);
                caseBandeirinha = String.isEmpty(commentCase.MktPlaceBandeirinha__c) ? 'Vazio' : commentCase.MktPlaceBandeirinha__c;
                
                if(isCustomer) {
                    caseStatus = 'Aguardando resposta do Lojista';
                    
                } else if(isSeller) {
                    caseStatus = 'Aguardando resposta do Cliente';
                }
            }
            
            listCaseUpdate.add(new Case(Id = commentCase.Id, Status = caseStatus, MktPlaceBandeirinha__c = caseBandeirinha));
        }
        
        
        System.debug('@@@ listCaseUpdate @@@\n' + JSON.serializePretty(listCaseUpdate));
        
        if(!listCaseUpdate.isEmpty())
            Database.update(listCaseUpdate);
    }

}