src/objects/Case_Configuration__c.object
<CustomObject>
    <fields>
        <fullName>Level_1__c</fullName>
        <label>Nivel 1</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Level_2__c</fullName>
        <label>Nível 2</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Register_Type__c</fullName>
        <label>Tipo de Registro</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Workflow__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Workflow</label>
        <type>Checkbox</type>
    </fields>
    <label>Configuração de Caso</label>
    <nameField>
        <displayFormat>Config-{00000000}</displayFormat>
        <label>ID de Configuração Caso</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Configuração de Caso</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/CaseConfigurationDAO.cls
public class CaseConfigurationDAO {
	
	private static Map<String, Case_Configuration__c> caseConfigurationMapByLevel;
	
	
	public static Case_Configuration__c getCaseConfigurationByLevel(String level_1, String level_2){
		if(caseConfigurationMapByLevel == null){
			caseConfigurationMapByLevel = new Map<String, Case_Configuration__c>();
            for(Case_Configuration__c cc : getCaseConfigurationListByLevel(level_1, level_2)) {
				caseConfigurationMapByLevel.put(cc.Level_1__c.trim() + cc.Level_2__c.trim(), cc);
			}
		}
		
		String levelTrim = level_1.trim() + level_2.trim();
		return caseConfigurationMapByLevel.containsKey(levelTrim) ? caseConfigurationMapByLevel.get(levelTrim) : null;
	}
	
	public static List<Case_Configuration__c> getCaseConfigurationListByLevel(String level_1, String level_2){
        return [
            SELECT 	Register_Type__c, 
            		Workflow__c,
            		Level_1__c,
            		Level_2__c
            		
            FROM 	Case_Configuration__c
            WHERE 	Level_1__c = : level_1.trim()
            AND 	Level_2__c = : level_2.trim()
        ];
	}
	
}