src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>CorrectItemCode__c</fullName>
        <label>1. Código do item correto</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CustomerEmail__c</fullName>
        <label>E-mail do cliente</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Level_1__c</fullName>
        <label>Classificação</label>
        <picklist>
            <picklistValues>
                <fullName>Análise do Produto</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cadastro e seu espaço</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelamento</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Coleta e devolução</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Entrega com nota fiscal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Garantia estendida</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Nota Fiscal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Troca</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Entrega sem nota fiscal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Casos abertos pelo CD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>E-mail</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ligação</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Level_2__c</fullName>
        <label>Motivo do Contato</label>
        <picklist>
            <controllingField>Level_1__c</controllingField>
            <picklistValues>
                <fullName>Análise do Produto - Faltando acessórios</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Produto diferente do que constava no site</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Produto com preço | Forma de pagamento diferente do ato da compra</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Erro em promoção anunciada</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Problemas com o cadastro no site</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Informação de produto</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Informação de Cadastro</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Informação de cancelamento - procedimento e prazos</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Informação sobre a coleta / devolução</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Recontato com protocolo aberto ou dentro do prazo de coleta</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Informação de entrega procecimento e prazos</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Recontato com protocolo aberto ou dentro do prazo de entrega</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Informação de entrega procedimento e prazos</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Informação de garantia estendida</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Informações sobre notas fiscais / DANFE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Informação de troca - procedimento e prazos</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Solicitar similiar para troca</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Atraso - Pedido liberado faturamento - Não tem produto disponível</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Atraso - Pedido não liberado faturamento</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Atraso - Pedido liberado faturamento - Tem produto disponível</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Há item do pedido que não foi processado</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Boleto com código inválido</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pagamento do pedido não foi confirmado</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Abertura de cancelamento ADM ou ML Admin</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dados para restituição de cancelamento ML Admin</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Reclamação de atraso na restituição ou estorno</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Solicitação de cancelamento em exceção</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Solicitar alteração no status restituição ou estorno</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Solicitar cancelamento de pedido liberado para faturamento</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Alterar endereço de coleta</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>NewEmailAlteration__c</fullName>
        <label>Novo e-mail para alteração</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PhoneNumber_1__c</fullName>
        <label>Telefone 1ª opção</label>
        <length>14</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PhoneNumber_2__c</fullName>
        <label>Telefone 2ª opção</label>
        <length>14</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ProblemTypeRegistration__c</fullName>
        <label>Tipo de problema com o cadastro</label>
        <picklist>
            <picklistValues>
                <fullName>Cliente não consegue modificar a senha (NÃO PREENCHER NOVO E-MAIL)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cliente não consegue modificar o e-mail</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cliente não acessa mais e-mail e deseja alterar</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

src/objects/CaseResolution__c.object
<CustomObject>
    <fields>
        <fullName>Action__c</fullName>
        <label>Ação</label>
        <picklist>
            <picklistValues>
                <fullName>Acompanhar solução</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Enviar para ativo posicionar cliente</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Alterada ocorrência no status restituição estorno</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Não foi possível alterar a ocorrência</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Posição sobre atraso na restituição/estorno</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dados enviados para restituição na conta bancária</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Divergência nos dados enviados para restituição</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Verificar previsão de entrega abaixo</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PASSE EXCEÇÃO Refat ainda não autorizado, estamos em negociação interna, se refaturado, será em ROT T</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PASSE EXCEÇÃO Transp está buscando o produto, se localizado, será devolvido, do contrário, refaturado em ROT T</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pedido está sendo devolvido, verificar data de devolução abaixo</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Entrega foi realizada | Enviar para ativo confirmar com o cliente</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Verificar protocolo de refaturamento já aberto</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Autorizada exceção da AVARIA PARCIAL | ATIVO ABRA OCORRÊNCIA!</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Endereçço alterado - Conforme solicitado</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Posicionar cliente</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Não tem produto | Enviar para comercial</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Processar troca ou cancelamento (restituição – compra boleto)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cliente decidiu cancelar</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Enviar para processamento gerar troca</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Enviar para comercial validar similar escolhido pelo cliente</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Posicionar cliente Produto enviado</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Verificar previsão de entrega abaixo (PREENCHER A PERGUNTA 2)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pedido está sendo devolvido, verificar data de devolução abaixo (PREENCHER A PERGUNTA 3)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Verificar protocolo de refaturamento já aberto (PREENCHER A PERGUNTA 4)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Autorizada exceção da AVARIA PARCIAL | ATIVO ABRA OCORRÊNCIA! (PREENCHER A PERGUNTA 5)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Resultado da acareação nas considerações finais (PREENCHER A PERGUNTA 6)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Acompanhar | Aguardar retorno da acareação</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Solicitado prioridade na expedição | Posicionar cliente</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Caso__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Caso</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Resoluções</relationshipLabel>
        <relationshipName>Resolu_es_de_Casos</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CorrectItemCode__c</fullName>
        <label>Código do item correto</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>FinalPositionCustomer__c</fullName>
        <label>Qual a posição final para o cliente</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>PosicionamentoFinalSobreErro__c</fullName>
        <label>Posicionamento final sobre o erro</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>ResponsibleForError__c</fullName>
        <label>Responsável pelo erro</label>
        <picklist>
            <picklistValues>
                <fullName>CD - Armazenamento</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CD - Expedição</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CD - Recebimento</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Comercial Ecomm</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Comercial Rede</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CSC Cadastro</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fornecedor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Marketing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Multimídia</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>WhatResolved__c</fullName>
        <label>O que ficou resolvido?</label>
        <picklist>
            <picklistValues>
                <fullName>Reenviar produto</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cliente decidiu cancelar pedido | Foi aberta OC | Solicitar SIM e encerrar fluxo</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fechar fluxo | Cliente confirmou recebimento do produto</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Resolução de Caso</label>
    <nameField>
        <displayFormat>RC-{000}</displayFormat>
        <label>Número da Resolução</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Resoluções de Casos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/clsTestTrgResolucao.cls
@isTest(SeeAllData=true)
public class clsTestTrgResolucao
{
    static testMethod void testaResolucao()
    {
        RecordType recTypeCase = [SELECT Id FROM RecordType WHERE SObjectType = 'Case' AND Name = 'Cadastro e seu espaço'];
        Case csTest = new Case();
        csTest.RecordTypeId = recTypeCase.Id;
        csTest.PhoneNumber_1__c = '1126251414';
        csTest.PhoneNumber_2__c = '11986521400';
        csTest.CustomerEmail__c = 'filipe.marino@makeitsimple.com.br';
        csTest.ProblemTypeRegistration__c = 'Cliente não consegue modificar o e-mail';
        csTest.Level_1__c = 'Cadastro e seu espaço';
        csTest.Level_2__c = 'Produto diferente do que constava no site';
        csTest.Description = 'Teste';
        csTest.NewEmailAlteration__c='rafael.souza@teste.com.br';
        
        insert csTest;
    
        Set<String> tiposReg = new Set<String>();
        tiposReg.add('Produto Devolvido');
        tiposReg.add('Pendencia Entrega');
        tiposReg.add('Análise do Produto');
        tiposReg.add('Erro de Cadastro');
        tiposReg.add('Garantia Estendida');
        
        List<RecordType> recTypeCaseList = [SELECT Id, Name FROM RecordType WHERE SObjectType = 'CaseResolution__c' AND Name IN :tiposReg];
        
        String idProdDev = '';
        String idPendEnt = '';
        String idAnProd = '';
        String idErrCad = '';
        String idGarantEst = '';
        
        for(RecordType recType : recTypeCaseList)
        {
            if (recType.Name == 'Produto Devolvido')
            {
                idProdDev = recType.Id;
            }
            
            if (recType.Name == 'Pendencia Entrega')
            {
                idPendEnt = recType.Id;
            }
            
            if (recType.Name == 'Análise do Produto')
            {
                idAnProd = recType.Id;
            }
            
            if (recType.Name == 'Erro de Cadastro')
            {
                idErrCad = recType.Id;
            }
            
            if (recType.Name == 'Garantia Estendida')
            {
                idGarantEst = recType.Id;
            }
        }
        
        //CaseResolution__c csResol = new CaseResolution__c();
        CaseResolution__c csResol = new CaseResolution__c();
        csResol.RecordTypeId = idPendEnt;
        csResol.WhatResolved__c = 'Fechar fluxo | Cliente confirmou recebimento do produto';
        csResol.Action__c = 'Acompanhar solução';
        csResol.Caso__c = csTest.Id;
        csResol.FinalPositionCustomer__c = 'Teste';
        insert csResol;
        
        update csResol;
        
        csResol = new CaseResolution__c();
        csResol.RecordTypeId = idPendEnt;
        csResol.WhatResolved__c = 'Reenviar produto';
        csResol.Action__c = 'Acompanhar solução';
        csResol.Caso__c = csTest.Id;
        csResol.FinalPositionCustomer__c = 'Teste';
        insert csResol;
        
        update csResol;
        
        csResol = new CaseResolution__c();
        csResol.RecordTypeId = idGarantEst;
        csResol.Action__c = 'Enviar para ativo posicionar cliente';
        csResol.Caso__c = csTest.Id;
        insert csResol;
        
        update csResol;
        
        csResol.Action__c = 'Acompanhar solução';
        csResol.PosicionamentoFinalSobreErro__c = 'Teste';
        update csResol;
        
        //csResol = new CaseResolution__c();
        //csResol.RecordTypeId = idAnProd;
        //csResol.Action__c = 'Enviar para ativo posicionar cliente';
        //csResol.Caso__c = csTest.Id;
        //csResol.ResponsibleForError__c = 'Fornecedor';
        //csResol.CorrectItemCode__c = 141414;
        //csResol.ErrorCausedRating__c = 'Erro na cor';
        //csResol.ProposedSolutionforComercialSuport__c = 'Fornecedor enviará peça ou produto';
        //insert csResol;
        
        //update csResol;
    }	
}