src/objects/IntegrationSetup__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Endpoint__c</fullName>
        <label>Endpoint</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Integration setup</label>
</CustomObject>

src/classes/MktPlace_GibaIntegrationServiceMock.cls
/**
*
*
*/
@isTest(SeeAllData=true)
global class MktPlace_GibaIntegrationServiceMock implements HttpCalloutMock {
	/**
	*
	*
	*/
    global HTTPResponse respond( HTTPRequest req ) {
        System.assertEquals( IntegrationSetup__c.getValues( 'MESSAGES' ).Endpoint__c, req.getEndpoint() );
        System.assertEquals( 'POST', req.getMethod() );
        
        // Create a fake response
        HttpResponse res = new HttpResponse();
        res.setHeader( 'Content-Type', 'application/json' );
        res.setBody( '' );
        //res.setStatusCode( 201 );
        res.setStatusCode( 200 );
        return res;
    }
}