src/objects/Queue__c.object
<CustomObject>
    <fields>
        <fullName>EventName__c</fullName>
        <label>Event name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ExceptionStackTrace__c</fullName>
        <label>Exception stack trace</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>IgnoredByTrigger__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Ignored by trigger</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Payload__c</fullName>
        <label>Payload</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>CREATED</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>SUCCESS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ERROR</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Queue</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Queue</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Queues</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/QueueDAO.cls
/**
	*@author Diego Moreira
	*@class Classe DAO do objeto queue
*/
public with sharing class QueueDAO extends SObjectDAO {
	/*
		Singleton
    */  
	private static final QueueDAO instance = new QueueDAO();    
    private QueueDAO(){}
    
    public static QueueDAO getInstance() {
        return instance;
    }

    /**
		*Retorna a fila pelo Id
		*@param queueId id da fila para reprocessamento
    */
    public List<Queue__c> getQueueById( String queueId ) {
    	return [SELECT Id, Name, EventName__c, Status__c, Payload__c, IgnoredByTrigger__c, ExceptionStackTrace__c
					FROM Queue__c
					WHERE Id = :queueId];
    } 

    /**
		*Retorna filas por status
		*@param queueStatus Status da fila para filtro
	*/
	public List<Queue__c> getQueueByStatus( String queueStatus ) {
		return [SELECT Id, Name, EventName__c, Status__c, Payload__c, CreatedDate, IgnoredByTrigger__c 
					FROM Queue__c
					WHERE Status__c = :queueStatus
					order by Name desc];
	}

	/**
		*Retorna filas por status
		*@param queueStatus Status da fila para filtro
	*/
	public List<Queue__c> getQueueByStatus( List<String> queueStatus ) {
		return [SELECT Id, Name, EventName__c, Status__c, Payload__c, CreatedDate, IgnoredByTrigger__c
					FROM Queue__c
					WHERE Status__c in :queueStatus
					order by Name desc
					Limit 50];
	}

}